name: Teste Container
on: 
    workflow_dispatch:  
jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Teste local
              run: cat /etc/os-release


            - name: Teste container
              uses: docker://alpine:latest 
              with: 
                entrypoint: cat 
                args: /etc/os-release